### ISSUE TITLE
Issue on page /Part_3_Python/M3/tasks/team_2/a/instructions.html

### ISSUE THREAD

**Issue by Sudeep204** [Purdue-ENGR-13300/fall-2024#27] opened 2024-09-19 15:04 UTC
![Screenshot 2024-09-19 110241](https://github.com/user-attachments/assets/279edbd2-32c5-49de-b27a-7d9a1e9ab9c5)
![Screenshot 2024-09-19 110335](https://github.com/user-attachments/assets/34b15b96-6f0d-4c15-b40b-a7e76a05ef90)

**Comment by jhcole** [comment] 2024-10-18 19:41
Closing, as it's unclear what the issue is here.

Also, please don't post solution code publicly.

**Closed as completed by jhcole** 2024-10-18 19:41 UTC
